env/templates/700-jx-tenant-service-ing.yaml
to allow more REST calls through
=> fix: the ingress path for the tenant service

env/jx-app-sso/values.tmpl.yaml
=> chore: migrate to cloudbees sso

env/templates/700-jx-tenant-service-ing.yaml
to avoid breaking old commands + jxt versions
=> fix: lets expose the secured REST APIs on basic auth too

env/requirements.yaml
=> Chore: update jxui

env/jxui-arcalos/values.tmpl.yaml, env/requirements.yaml
Reverts arcalos-environments/environment-raccoonshimmer-dev#314
=> Revert "chore: try out segment updates"

env/jxui-arcalos/values.tmpl.yaml
=> chore: try out new jxui-backend

env/jx-app-sso/values.tmpl.yaml, env/jxui-arcalos/values.tmpl.yaml
This reverts commit cb24d918e9d7df9f329db3e5b0a013038baff16a.
Revert "chore: try out new jxui-backend"
This reverts commit 6042a6d7f9100597e19b2a57b84c4ec920ad29d5.
Revert "fix: oops, syntax error"
This reverts commit df8c9a08ab4d377a41391bdb5db29c7e0340097a.
Revert "chore: test out cloudbees connector for dex"
This reverts commit 7d228bc008c9b56fd920a9eb9fba2e034f5300bd.
=> Revert "Update values.tmpl.yaml"

env/jx-app-sso/values.tmpl.yaml
Reverts arcalos-environments/environment-raccoonshimmer-dev#430
=> Revert "chore: switch to cloudbees connector"

env/requirements.yaml
Reverts arcalos-environments/environment-raccoonshimmer-dev#869
=> Revert "chore: downgrade lighthouse-githubapp to 0.0.405"

env/templates/arcalos-config-configmap.yaml
Signed-off-by: Mark Cox <markcox20@hotmail.com>
=> feat: add arcalos configuration configmap

env/templates/arcalos-prod-secret.yaml, env/values.tmpl.yaml
=> chore: add arcalos-prod-secret for alpha producer env

env/jx-tenant-service/values.tmpl.yaml, env/templates/arcalos-alpha-prod-secret.yaml
=> chore: move to arcalos-alpha-prod-secret

env/jx-tenant-service/values.tmpl.yaml, env/lighthouse-githubapp/values.tmpl.yaml, env/templates/arcalos-config-configmap.yaml
=> chore: update play to use aps alpha environment

env/jxui-arcalos/values.tmpl.yaml
=> fix: update jxui-backend service account

OWNERS
=> fix: added cjxd-bot to OWNERS file

OWNERS
=> chore: owners file maintenance

env/templates/701-boot-tenant-service-ing.yaml
Reverts arcalos-environments/environment-raccoonshimmer-dev#1323
=> revert: white list the workspace/roles endpoint

env/jxui-arcalos/values.tmpl.yaml, env/requirements.yaml
=> fix: update name for SSO connector

env/templates/700-jx-tenant-service-ing.yaml
#https://github.com/cloudbees/arcalos/issues/945
=> chore: add workspace endpoint to tenant service ing

env/jxui-arcalos/values.tmpl.yaml
Reverts arcalos-environments/environment-raccoonshimmer-dev#1708
=> Revert "fix: attempt to disable sso for jxui-arcalos"
